# Generated by Django 6.0.3 on 2026-03-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('saas', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feetype'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='studentscholarship',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.scholarship'),
        ),
        migrations.AddField(
            model_name='studentscholarship',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('tenant', 'code', 'academic_year', 'program', 'class_level')},
        ),
        migrations.AlterUniqueTogether(
            name='feetype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructureitem',
            unique_together={('fee_structure', 'fee_type')},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'fee_type')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentplan',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='scholarship',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='studentscholarship',
            unique_together={('student_profile', 'scholarship')},
        ),
    ]
