# Generated by Django 6.0.3 on 2026-03-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('hr', '0001_initial'),
        ('saas', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmembership',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='classmembership',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='saas.campus'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='hr.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_schedules', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='saas.campus'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='course_schedules', to='academics.class'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_schedules', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_schedules', to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='academics.course'),
        ),
        migrations.AddField(
            model_name='instructorassignment',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class'),
        ),
        migrations.AddField(
            model_name='instructorassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='academics.course'),
        ),
        migrations.AddField(
            model_name='instructorassignment',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='hr.staffprofile'),
        ),
        migrations.AddField(
            model_name='instructorassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='instructor_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='academics.instructorassignment'),
        ),
        migrations.AddField(
            model_name='module',
            name='course_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_modules', to='academics.courseversion'),
        ),
        migrations.AddField(
            model_name='program',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='saas.campus'),
        ),
        migrations.AddField(
            model_name='program',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programversion',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programrequirement',
            name='program_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='academics.programversion'),
        ),
        migrations.AddField(
            model_name='module',
            name='program_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.programversion'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='course_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='academics.courseschedule'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='term',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='instructorassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='academics.term'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_schedules', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classmembership',
            unique_together={('class_obj', 'student_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('tenant', 'campus', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='courseversion',
            unique_together={('course', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='programversion',
            unique_together={('program', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('program_version', 'course_version')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleday',
            unique_together={('course_schedule', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='instructorassignment',
            unique_together={('staff_profile', 'course', 'class_obj', 'term')},
        ),
    ]
