# Generated by Django 6.0.3 on 2026-03-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0001_initial'),
        ('common', '0001_initial'),
        ('finance', '0001_initial'),
        ('hr', '0001_initial'),
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_number', models.CharField(max_length=50)),
                ('enrolled_on', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('class_obj', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class')),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentplan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.enrollment')),
            ],
            options={
                'db_table': 'enrollment_status_history',
            },
        ),
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_type', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardian_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('student_number', models.CharField(max_length=50)),
                ('admitted_on', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(default='active', max_length=50)),
                ('admission_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.admissionoffer')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='saas.campus')),
                ('current_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='academics.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
                'unique_together': {('tenant', 'student_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to='common.fileupload')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Papua New Guinea', max_length=120)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_addresses',
            },
        ),
        migrations.CreateModel(
            name='ReEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_on', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('new_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_reenrollment_set', to='students.enrollment')),
                ('previous_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_reenrollment_set', to='students.enrollment')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollments', to='students.studentprofile')),
            ],
            options={
                'db_table': 'reenrollments',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentprofile'),
        ),
        migrations.CreateModel(
            name='StudentProgramHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.program')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_history', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_program_history',
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_status_history',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawal_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='students.enrollment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='students.studentprofile')),
            ],
            options={
                'db_table': 'withdrawals',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('guardian_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_students', to='students.guardianprofile')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_guardians',
                'unique_together': {('student_profile', 'guardian_profile')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student_profile', 'program', 'academic_year', 'term'), ('tenant', 'enrollment_number')},
        ),
        migrations.CreateModel(
            name='WithdrawalClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clearance_status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='students.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_clearances',
                'unique_together': {('withdrawal', 'department')},
            },
        ),
    ]
