# Generated by Django 6.0.3 on 2026-03-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('hr', '0001_initial'),
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.TextField()),
                ('approval_status', models.CharField(default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_adjustment_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_adjustment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_adjustments',
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('component_order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='academics.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.term')),
            ],
            options={
                'db_table': 'assessment_components',
            },
        ),
        migrations.CreateModel(
            name='AssessmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_text', models.TextField()),
                ('visibility', models.CharField(default='internal', max_length=20)),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staffprofile')),
            ],
            options={
                'db_table': 'assessment_feedback',
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contributes_to_final', models.BooleanField(default=True)),
                ('assessment_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.assessmentcomponent')),
                ('class_obj', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class')),
                ('course_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.courseschedule')),
            ],
            options={
                'db_table': 'assessment_items',
            },
        ),
        migrations.CreateModel(
            name='GradePublicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch_name', models.CharField(max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'db_table': 'grade_publication_batches',
            },
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50)),
                ('pass_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant')),
            ],
            options={
                'db_table': 'grading_schemes',
            },
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.gradingscheme'),
        ),
        migrations.CreateModel(
            name='GradingSchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_letter', models.CharField(max_length=10)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remark', models.CharField(blank=True, max_length=120)),
                ('grading_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.gradingscheme')),
            ],
            options={
                'db_table': 'grading_scheme_items',
            },
        ),
        migrations.CreateModel(
            name='PassFailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule_name', models.CharField(max_length=120)),
                ('minimum_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_attendance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_all_components_passed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant')),
            ],
            options={
                'db_table': 'pass_fail_rules',
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adjusted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='assessments.assessmentitem')),
                ('marked_by_staff_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staffprofile')),
            ],
            options={
                'db_table': 'student_assessments',
            },
        ),
    ]
