# Generated by Django 6.0.3 on 2026-03-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmentfeedback',
            name='student_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='assessments.studentassessment'),
        ),
        migrations.AddField(
            model_name='assessmentadjustment',
            name='student_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='assessments.studentassessment'),
        ),
        migrations.AlterUniqueTogether(
            name='gradingscheme',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomponent',
            unique_together={('tenant', 'course', 'term', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='gradingschemeitem',
            unique_together={('grading_scheme', 'grade_letter')},
        ),
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together={('assessment_item', 'student_profile')},
        ),
    ]
