# Generated by Django 6.0.3 on 2026-03-10 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('term', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'blueprint_academic_calendars',
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'blueprint_academic_sessions',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'blueprint_classrooms',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blueprint_programs',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('branch_code', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.CharField(blank=True, max_length=255)),
                ('subscription_status', models.CharField(default='active', max_length=20)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blueprint_schools',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.academiccalendar')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_modules',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('credit_hours', models.IntegerField(default=0)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_courses',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='blueprint.school'),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('tuition', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_fee_structures',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_enquiries',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_departments',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.course')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.academicsession')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.module')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_course_schedules',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='blueprint.school'),
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('component_type', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.courseschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_assessment_components',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=120)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_activity_logs',
            },
        ),
        migrations.AddField(
            model_name='academicsession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='blueprint.school'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='blueprint.school'),
        ),
        migrations.CreateModel(
            name='SPR',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('remarks', models.CharField(blank=True, max_length=20)),
                ('pass_cutoff', models.DecimalField(decimal_places=2, default=75, max_digits=5)),
                ('training_manager_status', models.CharField(default='pending', max_length=30)),
                ('registrar_status', models.CharField(default='pending', max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.courseschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_spr',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_staff',
            },
        ),
        migrations.CreateModel(
            name='SPRVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('spr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blueprint.spr')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.staff')),
            ],
            options={
                'db_table': 'blueprint_spr_versions',
            },
        ),
        migrations.AddField(
            model_name='spr',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_submitted', to='blueprint.staff'),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=30)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.classroom')),
                ('course_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.courseschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.staff')),
            ],
            options={
                'db_table': 'blueprint_exam_schedules',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to='blueprint.staff'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.staff'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.staff'),
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=80)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='blueprint.staff')),
            ],
            options={
                'db_table': 'blueprint_staff_roles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('intake_batch', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='active', max_length=30)),
                ('request_credits', models.IntegerField(default=5)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_students',
            },
        ),
        migrations.AddField(
            model_name='spr',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.student'),
        ),
        migrations.CreateModel(
            name='ExamPermit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_verified', models.BooleanField(default=False)),
                ('training_manager_approved', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('is_used', models.BooleanField(default=False)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.examschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.student')),
            ],
            options={
                'db_table': 'blueprint_exam_permits',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.courseschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.student')),
            ],
            options={
                'db_table': 'blueprint_attendance_records',
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_special_exam', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.assessmentcomponent')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.student')),
            ],
            options={
                'db_table': 'blueprint_student_assessments',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='enrolled', max_length=30)),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.courseschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.student')),
            ],
            options={
                'db_table': 'blueprint_student_enrollments',
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_plan', models.CharField(default='monthly', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='unpaid', max_length=30)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.feestructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.student')),
            ],
            options={
                'db_table': 'blueprint_student_fees',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(blank=True, max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.studentfee')),
            ],
            options={
                'db_table': 'blueprint_payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='MonthlyInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.studentfee')),
            ],
            options={
                'db_table': 'blueprint_monthly_installments',
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=80)),
                ('details', models.TextField(blank=True)),
                ('credits_used', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.student')),
            ],
            options={
                'db_table': 'blueprint_student_requests',
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.school')),
            ],
            options={
                'db_table': 'blueprint_website_content',
            },
        ),
    ]
