# Generated by Django 6.0.3 on 2026-03-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='attendancewarning',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='attendancewarning',
            name='generated_from_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancesummary'),
        ),
        migrations.AddField(
            model_name='attendancewarning',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_warnings', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendancewarning',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='studentattendancerecord',
            name='attendance_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='studentattendancerecord',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='student_attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='attendance.studentattendancerecord'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('course_schedule', 'session_date', 'starts_at')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('student_profile', 'course', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendancerecord',
            unique_together={('attendance_session', 'student_profile')},
        ),
    ]
