# Generated by Django 6.0.3 on 2026-03-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('exams', '0001_initial'),
        ('hr', '0001_initial'),
        ('saas', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattendance',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.staffprofile'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staffprofile'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='examresultadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_adjustment_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresultadjustment',
            name='exam_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='exams.examresult'),
        ),
        migrations.AddField(
            model_name='examresultadjustment',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_result_adjustment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examseating',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='academics.class'),
        ),
        migrations.AddField(
            model_name='examseating',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='examseating',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='examseating',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='examattendance',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.examtype'),
        ),
        migrations.AlterUniqueTogether(
            name='examseating',
            unique_together={('exam_session', 'class_obj', 'seat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam_session', 'student_profile', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='examattendance',
            unique_together={('exam_session', 'student_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('tenant', 'exam_type', 'term', 'name')},
        ),
    ]
